#!/usr/bin/env python3
"""Replace the bottom tab bar with one canonical component on every screen.

Stitch generated the tab bar independently per screen: nine different class lists,
three `<nav>` elements containing no items at all, six screens missing it entirely,
and "Credit Card" on one screen against "Credit card" on the rest. Padding ranged
from `py-2` to `py-3`, some carried `md:hidden`, some `rounded-t-xl`, some `dark:`
variants, and the active item was a cyan pill rather than the filled dark icon the
real app uses.

The markup here is plain CSS rather than Tailwind utilities on purpose: each screen
ships its own inline Tailwind config, so utilities do not render identically across
files. A self-contained block does.

Matches the reference screenshot: white bar, soft top shadow, five equal columns,
24px icon over a 10px label, active item in Ink with a filled icon.

    python3 tools/normalize-chrome.py
    python3 tools/normalize-chrome.py --check
"""
from __future__ import annotations

import pathlib
import re
import sys

SCREENS = pathlib.Path("docs/screens")

# Top-level app screens carry the tab bar. Modal sheets and full-page flows do not:
# the bar is not reachable from them, and on screen 12 it overlapped the sheet.
WITH_NAV = {
    "01-pockets-home", "02-food-pocket-detail", "03-transit-low-balance",
    "05-rent-shared-pocket", "08-card-details-wallet", "10-transaction-reroute",
    "11-pocket-perks", "13-semester-runway", "15-pockets-home-alt",
    "16-food-detail-alt",
}

# Icons chosen to match the reference: filled house, $ in a circle, card, bar chart,
# rosette. Pockets lives under Banking, so Banking is the active tab throughout.
ITEMS = [
    ("home", "Home", False),
    ("paid", "Banking", True),
    ("credit_card", "Credit card", False),
    ("bar_chart", "Invest", False),
    ("workspace_premium", "Loans", False),
]

STYLE = """
        /* Canonical bottom tab bar — see tools/normalize-chrome.py. Plain CSS so it
           renders identically across screens that each ship their own Tailwind
           config. */
        .bottom-nav {
            position: fixed;
            left: 0; right: 0; bottom: 0;
            z-index: 50;
            display: flex;
            background: #FFFFFF;
            box-shadow: 0 -4px 20px rgba(32, 23, 71, 0.06);
            padding: 8px 0 10px;
        }
        .bottom-nav__item {
            flex: 1 1 0;
            min-width: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            gap: 4px;
            padding: 6px 2px;
            text-decoration: none;
            color: #53565A;
            font-family: Inter, system-ui, sans-serif;
            font-size: 10px;
            font-weight: 500;
            line-height: 1.2;
            letter-spacing: 0;
            text-align: center;
        }
        .bottom-nav__item .material-symbols-outlined {
            font-size: 24px;
            line-height: 1;
        }
        .bottom-nav__item[aria-current="page"] {
            color: #201747;
            font-weight: 700;
        }
        .bottom-nav__item[aria-current="page"] .material-symbols-outlined {
            font-variation-settings: 'FILL' 1;
        }
        /* Keep content clear of the bar. Lower specificity than a Tailwind
           utility, so a screen that already sets its own padding still wins. */
        body { padding-bottom: 84px; }
"""

MARKER = "<!-- BottomNav: canonical, generated by tools/normalize-chrome.py -->"



# Masked card numbers appeared in two formats: "•••• 4417" on three screens and the
# full "•••• •••• •••• 5521" on one. The short form is what a card summary shows.
def rewrite_card_masks(html: str) -> tuple[int, str]:
    fixed, n = re.subn(r"(?:[•·]{4}\s+){2,}([•·]{4}\s+)?(\d{4})", r"•••• \2", html)
    return n, fixed


# Top-bar icon buttons came in five treatments: a 44px circle with a filled
# background, a 44px circle without one, and three bare icons with no hit area at
# all. The reference screens show bare icons on the coloured header, so the visible
# circle goes and the 44px target stays.
TOPBAR_ICONS = ("arrow_back", "chevron_left", "more_horiz", "more_vert")
TOPBAR_CLASSES = "w-11 h-11 flex items-center justify-center rounded-full transition-colors"


def rewrite_topbar_buttons(html: str) -> tuple[int, str]:
    count = 0

    def sub(m: re.Match) -> str:
        nonlocal count
        attrs, inner = m.group("attrs"), m.group("inner")
        if not any(i in inner for i in TOPBAR_ICONS):
            return m.group(0)
        cls = re.search(r'class="([^"]*)"', attrs)
        existing = cls.group(1).split() if cls else []
        # Keep the colour, drop the filled circle and any ad-hoc sizing.
        colour = [c for c in existing if c.startswith(("text-", "dark:text-"))]
        want = " ".join(TOPBAR_CLASSES.split() + colour)
        if cls and cls.group(1) == want:
            return m.group(0)
        count += 1
        rebuilt = re.sub(r'class="[^"]*"', 'class="%s"' % want, attrs) if cls \
            else attrs + ' class="%s"' % want
        return "<button%s>%s</button>" % (rebuilt, inner)

    html = re.sub(r'<button(?P<attrs>[^>]*)>(?P<inner>\s*<span[^>]*>[^<]*</span>\s*)</button>',
                  sub, html)
    return count, html


def nav_html() -> str:
    rows = []
    for icon, label, active in ITEMS:
        attr = ' aria-current="page"' if active else ""
        rows.append(
            f'    <a class="bottom-nav__item" href="#"{attr}>'
            f'<span class="material-symbols-outlined">{icon}</span>'
            f"<span>{label}</span></a>"
        )
    return (f'{MARKER}\n<nav class="bottom-nav" aria-label="Primary">\n'
            + "\n".join(rows) + "\n</nav>\n")


def strip_nav(html: str) -> tuple[str, int]:
    html, n = re.subn(r"[ \t]*" + re.escape(MARKER) + r"\n?", "", html)
    html, m = re.subn(r"[ \t]*<nav\b.*?</nav>[ \t]*\n?", "", html, flags=re.S)
    # Comments that introduced the old bar would otherwise dangle.
    html, _ = re.subn(r"[ \t]*<!--\s*(?:Bottom\s*Nav\w*|BottomNavBar)[^>]*-->\n?", "", html,
                      flags=re.I)
    # Collapse the gap the removal leaves, so re-running is a no-op.
    html = re.sub(r"\n{3,}(?=</body>)", "\n", html)
    return html, n + m


def ensure_style(html: str) -> str:
    if ".bottom-nav__item" in html:
        return html
    if "</style>" in html:
        return html.replace("</style>", STYLE + "    </style>", 1)
    return html.replace("</head>", f"<style>{STYLE}</style>\n</head>", 1)


def main() -> int:
    check = "--check" in sys.argv
    changed = 0
    for path in sorted(SCREENS.glob("*.html")):
        original = path.read_text(encoding="utf-8")
        stem = path.stem
        html, removed = strip_nav(original)
        n_mask, html = rewrite_card_masks(html)
        n_btn, html = rewrite_topbar_buttons(html)

        if stem in WITH_NAV:
            html = ensure_style(html)
            html = html.replace("</body>", nav_html() + "</body>", 1)
            state = "canonical nav"
        else:
            state = "no nav (modal/full-page)"

        extras = []
        if n_mask:
            extras.append(f"{n_mask} card mask")
        if n_btn:
            extras.append(f"{n_btn} top-bar buttons")
        if html != original:
            changed += 1
            state += f" (replaced {removed})" if removed else " (added)"
            if extras:
                state += " + " + ", ".join(extras)
            if not check:
                path.write_text(html, encoding="utf-8")
        else:
            state = "already canonical"
        print(f"  {path.name:<30} {state}")

    verb = "would update" if check else "updated"
    print(f"\n{verb} {changed} of 16 screens")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
